# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: dolphin
    CORE_ARGS: -DLIBRETRO=ON
    
variables:
  GIT_SUBMODULE_STRATEGY: normal

.core-linux-defs:
  extends: .core-defs
  variables:
    CORE_ARGS: -DLIBRETRO=ON -DENABLE_QT=OFF

.core-windows-defs:
  extends: .core-defs
  variables:
    CORE_ARGS: -DLIBRETRO=ON -DENABLE_QT=OFF

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-msvc19.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'
    
  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-msvc19-cmake-x86_64
    - .core-windows-defs
  after_script:
    - move-Item "Binary\$Env:LIBNAME" "$Env:LIBNAME" -Force -ErrorAction SilentlyContinue

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-linux-defs
    
################################### CELLULAR #################################
# Android ARMv8a
libretro-build-android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs
