language:
- cpp
# - objective-c

install:
- sudo add-apt-repository -y ppa:fransschreuder1/usbpicprog-stable
- sudo apt-get -qq update
- sudo apt-get -qq install git cmake gettext wx2.9-headers libwxbase2.9-dev libwxgtk2.9-dev libgtk-3-dev libwayland-dev libsdl1.2-dev nvidia-cg-toolkit libxrandr-dev libxext-dev libglew-dev libavcodec-dev libavformat-dev libsoil-dev libsfml-dev libopenal-dev libao-dev libasound2-dev libpulse-dev libportaudio-dev libsoundtouch-dev libbluetooth-dev libreadline-dev libswscale-dev liblzo2-dev
- nproc=$((`nproc` / 2))

# - brew update
# - brew install cmake
# - nproc=4

script:
- cmake . && make -j $nproc
