sudo: false
language: cpp
services: docker
cache: ccache
compiler:
  - gcc
addons:
  apt:
    sources:
    #- ubuntu-toolchain-r-test
    packages:
    #- g++-8
    #- cmake
    - p7zip-full
install:
#- "[ $CXX = g++ ] && export CXX=g++-8 || true"
#- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
- mkdir -p "$HOME/.ccache"
- docker pull quriouspixel/yuzu:20.04
- docker run -u root --env-file travis/common/travis-ci.env -v $(pwd):/dolphin -v "$HOME/.ccache":/root/.ccache quriouspixel/yuzu:20.04 /bin/bash /dolphin/travis/appimage/docker.sh
script:
  - ls -al


  
