name: Lint

on:
  push:
    branches: [ ios-jb ]
  pull_request:
    branches: [ ios-jb ]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Lint
        run: | 
          git fetch origin ${{ github.base_ref }}
          echo "sha ${{ github.sha }}"
          ./Tools/lint.sh $(git rev-parse origin/${{ github.base_ref }})...
      
