# This is a basic workflow to help you get started with Actions

name: Linux CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Submoudle
    - name: Checkout Submodles
      run: git submodule update --init --recursive
    # Setup Build Directory
    - name: Make Build Directory
      run: mkdir build && cd build
    # Setup CMake
    - name: Setup CMake
    - uses: Symbitic/install-cmake@v0.1.0
      with:
        platform: linux
    # Run CMake
    - name: Run CMake
    - run: cmake .. -DLINUX_LOCAL_DEV=true
    # Build Project
    - name: Run Make
    - run: make
    # Configure Dolphin
    - name: Configure Dolphin
      run: cp -r ../Data/Sys/ Binaries/ && p -r ../Data/User/ Binaries/ && cp -r ../Data/Dolphin.png/ Binaries/ && touch Binaries/portable.txt
    # Upload Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DolphinMPN-Linux
        path: D:\a\dolphin-mpn\dolphin-mpn\Binary\x64
